/**
 * MVP Creature Species Definitions
 *
 * 20-creature MVP set as specified in Phase 1.
 * Full 50-creature launch set will expand in Phase 2.
 */

import type { CreatureSpecies } from '@/types';

export const MVP_CREATURES: CreatureSpecies[] = [
  // ─── Common S1 Class (Initiators) ────────────
  {
    id: 'first_pulse',
    name: 'First Pulse',
    resonanceClass: 's1',
    rarity: 'common',
    loreText: 'The smallest and most fundamental of all resonance creatures. It appears the moment a new captain makes their first recording — as if drawn by the sound of intention itself.',
    fieldNotes: 'Resting heart rate is your heart\'s baseline rhythm. The First Pulse celebrates the beginning of your measurement journey.',
    discoveryHint: 'Appears to those who make their first recording.',
    discoveryConditions: 'Manifests upon the captain\'s first heartbeat measurement.',
    triggerType: 'checkin_count',
    triggerConfig: { count: 1 },
    sortOrder: 1,
  },
  {
    id: 'dawn_moth',
    name: 'Dawn Moth',
    resonanceClass: 's1',
    rarity: 'common',
    loreText: 'Drawn to the first frequencies of each new cycle. Dawn Moths cluster around ships whose captains greet the new day with intention.',
    fieldNotes: 'Morning heart rate measurements often reflect overnight recovery. Checking in early helps establish your daily rhythm.',
    discoveryHint: 'Drawn to the first light of each cycle.',
    discoveryConditions: 'Appears to those who check in before the sun reaches its peak.',
    triggerType: 'morning_checkin',
    triggerConfig: { count: 1 },
    sortOrder: 2,
  },
  {
    id: 'kindling_spore',
    name: 'Kindling Spore',
    resonanceClass: 's1',
    rarity: 'common',
    loreText: 'A luminous seed that feeds on consistent rhythms. It takes three consecutive signals to coax it into visibility.',
    fieldNotes: 'Consistency in measurement is more valuable than any single reading. Three days of tracking begins to show your heart\'s patterns.',
    discoveryHint: 'Feeds on sustained rhythmic signals.',
    discoveryConditions: 'Manifests after three consecutive days of engine recordings.',
    triggerType: 'streak',
    triggerConfig: { days: 3 },
    sortOrder: 3,
  },
  {
    id: 'kindle_fox',
    name: 'Kindle Fox',
    resonanceClass: 's1',
    rarity: 'common',
    loreText: 'Clever and warm-furred, the Kindle Fox navigates by reading the thermal signatures of nearby vessels. It bonds with persistent captains.',
    fieldNotes: 'Five days of consistent tracking gives your heart rate data context — you can start to see how daily activities affect your rhythm.',
    discoveryHint: 'Bonds with those who persist through five cycles.',
    discoveryConditions: 'Appears after five consecutive days of engine recordings.',
    triggerType: 'streak',
    triggerConfig: { days: 5 },
    sortOrder: 4,
  },
  {
    id: 'blaze_polyp',
    name: 'Blaze Polyp',
    resonanceClass: 's1',
    rarity: 'common',
    loreText: 'A coral-like organism that anchors to ship hulls with a history of strong signals. It pulses in sync with the engine.',
    fieldNotes: 'After 10 check-ins, your data becomes statistically meaningful — trends begin to emerge from the noise.',
    discoveryHint: 'Anchors to vessels with rich signal histories.',
    discoveryConditions: 'Manifests after ten total engine recordings.',
    triggerType: 'checkin_count',
    triggerConfig: { count: 10 },
    sortOrder: 5,
  },

  // ─── Common S2 Class (Resolvers) ─────────────
  {
    id: 'drift_medusa',
    name: 'Drift Medusa',
    resonanceClass: 's2',
    rarity: 'common',
    loreText: 'Translucent and serene, the Drift Medusa floats through the quietest reaches of space. It is drawn to ships that record the stillness of sleep.',
    fieldNotes: 'Sleep is when your heart rate drops to its lowest. Logging sleep helps S1S2 understand your body\'s recovery patterns.',
    discoveryHint: 'Drawn to vessels that record the silence between beats.',
    discoveryConditions: 'Appears when a captain first logs their rest period.',
    triggerType: 'sleep_log',
    triggerConfig: { count: 1 },
    sortOrder: 6,
  },
  {
    id: 'settle_frog',
    name: 'Settle Frog',
    resonanceClass: 's2',
    rarity: 'common',
    loreText: 'Perfectly still. The Settle Frog does not hop — it simply arrives, and everything around it calms.',
    fieldNotes: 'Evening heart rate measurements capture your wind-down state. The difference between morning and evening readings reveals your daily range.',
    discoveryHint: 'Appears in the quiet hours.',
    discoveryConditions: 'Manifests when a captain checks in during the evening.',
    triggerType: 'evening_checkin',
    triggerConfig: { count: 1 },
    sortOrder: 7,
  },
  {
    id: 'hush_snail',
    name: 'Hush Snail',
    resonanceClass: 's2',
    rarity: 'common',
    loreText: 'Its spiral shell resonates at frequencies so low they\'re nearly inaudible. Only the most efficient engines attract the Hush Snail.',
    fieldNotes: 'A resting heart rate below 75 BPM is generally a sign of good cardiovascular fitness. Lower usually means your heart pumps more blood per beat.',
    discoveryHint: 'Attracted to the most efficient engine rhythms.',
    discoveryConditions: 'Appears when the engine rhythm falls below 75 cycles at rest.',
    triggerType: 'metric_threshold',
    triggerConfig: { metric: 'resting_heart_rate', operator: 'lt', value: 75 },
    sortOrder: 8,
  },
  {
    id: 'rest_pup',
    name: 'Rest Pup',
    resonanceClass: 's2',
    rarity: 'common',
    loreText: 'Small, curled up, perpetually hibernating. Rest Pups attach to ships whose captains value recovery as much as action.',
    fieldNotes: 'Consistent sleep logging helps you see how rest affects your heart rate. Five nights of data reveals your personal sleep-heart connection.',
    discoveryHint: 'Attaches to those who value recovery.',
    discoveryConditions: 'Manifests after five consecutive rest period logs.',
    triggerType: 'consecutive_sleep_logs',
    triggerConfig: { days: 5 },
    sortOrder: 9,
  },
  {
    id: 'dusk_firefly',
    name: 'Dusk Firefly',
    resonanceClass: 's2',
    rarity: 'common',
    loreText: 'A gentle blinking light in the deep. Dusk Fireflies appear in clusters around ships with long, unbroken signal trails.',
    fieldNotes: 'A 10-day streak means you\'ve built the core habit. Most health tracking apps lose users by day 7 — you\'re already ahead.',
    discoveryHint: 'Appears where signal trails burn longest.',
    discoveryConditions: 'Manifests after ten consecutive days of recordings.',
    triggerType: 'streak',
    triggerConfig: { days: 10 },
    sortOrder: 10,
  },

  // ─── Common Harmonic Class (Bridges) ─────────
  {
    id: 'balance_bug',
    name: 'Balance Bug',
    resonanceClass: 'harmonic',
    rarity: 'common',
    loreText: 'Perfectly symmetrical and dual-colored, the Balance Bug vibrates at a frequency exactly between S1 and S2.',
    fieldNotes: 'Logging all vital types in one day gives the most complete picture of your cardiovascular health.',
    discoveryHint: 'Vibrates between two frequencies simultaneously.',
    discoveryConditions: 'Appears when all vital types are recorded in a single cycle.',
    triggerType: 'full_data_day',
    triggerConfig: { count: 1 },
    sortOrder: 11,
  },
  {
    id: 'rhythm_seed',
    name: 'Rhythm Seed',
    resonanceClass: 'harmonic',
    rarity: 'common',
    loreText: 'A dormant seed that pulses at a steady rate, waiting for the right conditions to bloom. Three full-data cycles will wake it.',
    fieldNotes: 'Multiple days of complete data lets S1S2 start finding correlations between your metrics — how sleep affects HR, how activity changes HRV.',
    discoveryHint: 'Dormant — awaits sustained complete signals.',
    discoveryConditions: 'Manifests after three days with all vital types recorded.',
    triggerType: 'full_data_day',
    triggerConfig: { count: 3 },
    sortOrder: 12,
  },

  // ─── Uncommon S1 Class ───────────────────────
  {
    id: 'solar_fox',
    name: 'Solar Fox',
    resonanceClass: 's1',
    rarity: 'uncommon',
    loreText: 'Larger than the Kindle Fox, with a mane of solar flame. The Solar Fox leads packs through uncharted nebulae, following only the most dedicated signals.',
    fieldNotes: 'Two weeks of consistent tracking is a significant achievement. Your data now tells a story — trends, patterns, and your personal normal.',
    discoveryHint: 'Leads from the front, following the longest trails.',
    discoveryConditions: 'Appears after fourteen consecutive days of engine recordings.',
    triggerType: 'streak',
    triggerConfig: { days: 14 },
    sortOrder: 13,
  },
  {
    id: 'forge_salamander',
    name: 'Forge Salamander',
    resonanceClass: 's1',
    rarity: 'uncommon',
    loreText: 'Born in the heart of dying stars, the Forge Salamander reshapes itself continuously. It is drawn to vessels with deep signal archives.',
    fieldNotes: 'Fifty check-ins represents genuine commitment to understanding your heart. The depth of your data now enables meaningful health insights.',
    discoveryHint: 'Drawn to the deepest signal archives.',
    discoveryConditions: 'Manifests after fifty total engine recordings.',
    triggerType: 'checkin_count',
    triggerConfig: { count: 50 },
    sortOrder: 14,
  },

  // ─── Uncommon S2 Class ───────────────────────
  {
    id: 'lunar_moth',
    name: 'Lunar Moth',
    resonanceClass: 's2',
    rarity: 'uncommon',
    loreText: 'Its wings are vast and luminous, covered in patterns that shift with the ambient frequencies. The Lunar Moth appears only to those who truly value rest.',
    fieldNotes: 'Two weeks of sleep data reveals your sleep architecture — when you sleep deeply, when you wake, and how it all connects to your heart.',
    discoveryHint: 'Appears only to those who honor the quiet cycle.',
    discoveryConditions: 'Manifests after fourteen consecutive rest period logs.',
    triggerType: 'consecutive_sleep_logs',
    triggerConfig: { days: 14 },
    sortOrder: 15,
  },
  {
    id: 'glacier_tortoise',
    name: 'Glacier Tortoise',
    resonanceClass: 's2',
    rarity: 'uncommon',
    loreText: 'Ancient and slow, its crystalline shell resonates at the lowest measurable frequencies. Only the most efficient engines can attract it.',
    fieldNotes: 'A resting heart rate below 65 BPM recorded multiple times suggests excellent cardiovascular efficiency.',
    discoveryHint: 'Resonates only with the most efficient engines.',
    discoveryConditions: 'Appears when the engine rhythm falls below 65 cycles at rest, five times.',
    triggerType: 'metric_threshold_repeated',
    triggerConfig: { metric: 'resting_heart_rate', operator: 'lt', value: 65, count: 5 },
    sortOrder: 16,
  },

  // ─── Uncommon Harmonic Class ─────────────────
  {
    id: 'mirror_fish',
    name: 'Mirror Fish',
    resonanceClass: 'harmonic',
    rarity: 'uncommon',
    loreText: 'Perfectly symmetrical in every dimension. The Mirror Fish swims in patterns that perfectly reflect the data streams of its host vessel.',
    fieldNotes: 'Seven consecutive days of complete data logging creates a full weekly portrait of your cardiovascular health — the gold standard for personal tracking.',
    discoveryHint: 'Swims in perfect symmetry with complete signals.',
    discoveryConditions: 'Manifests after seven consecutive days with all vital types recorded.',
    triggerType: 'consecutive_full_data_days',
    triggerConfig: { days: 7 },
    sortOrder: 17,
  },
  {
    id: 'pendulum_moth',
    name: 'Pendulum Moth',
    resonanceClass: 'harmonic',
    rarity: 'uncommon',
    loreText: 'Swinging between two states with metronomic precision, the Pendulum Moth marks the passage of every seventh cycle with a brief, beautiful flash.',
    fieldNotes: 'Reaching your first Listening Post means you\'ve traveled through seven star systems. Your journey is taking shape.',
    discoveryHint: 'Marks the passage of every seventh cycle.',
    discoveryConditions: 'Manifests when the first Listening Post is reached.',
    triggerType: 'listening_post_reached',
    triggerConfig: { count: 1 },
    sortOrder: 18,
  },
  {
    id: 'phase_spider',
    name: 'Phase Spider',
    resonanceClass: 'harmonic',
    rarity: 'uncommon',
    loreText: 'Existing simultaneously in two vibrational states, the Phase Spider weaves webs across dimensional boundaries. Its presence is a mark of sustained dedication.',
    fieldNotes: 'Three weeks of daily tracking builds a robust health profile. Patterns that seemed random at day 7 become clear trends by day 21.',
    discoveryHint: 'Weaves across dimensional boundaries.',
    discoveryConditions: 'Manifests after twenty-one consecutive days of recordings.',
    triggerType: 'streak',
    triggerConfig: { days: 21 },
    sortOrder: 19,
  },
  {
    id: 'tide_crab',
    name: 'Tide Crab',
    resonanceClass: 'harmonic',
    rarity: 'uncommon',
    loreText: 'Moves with the predictable rhythm of cosmic tides. The Tide Crab is ancient — it remembers every signal ever recorded in its territory.',
    fieldNotes: 'One hundred check-ins. Your commitment to understanding your heart has generated a genuinely valuable health dataset.',
    discoveryHint: 'Remembers every signal in its territory.',
    discoveryConditions: 'Manifests after one hundred total engine recordings.',
    triggerType: 'checkin_count',
    triggerConfig: { count: 100 },
    sortOrder: 20,
  },
];
